name: very-first-workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t tomieq/swift_app:1.0 .
      - run: docker run --rm -it --name swift_app_1 --env URL=traffic.com/open-telemetry tomieq/swift_app:1.0