name: very-first-workflow-on-mac
run-name: ${{ github.actor }} is learning GitHub Actions on Mac VM
on: [push]
jobs:
  sample-job:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: swift --version